name: invoice_generator
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - flask=3.0.0
  - openpyxl=3.1.2
  - werkzeug=3.0.1
  - jinja2=3.1.2
  - markupsafe=2.1.3
  - itsdangerous=2.1.2
  - click=8.1.7
  - blinker=1.7.0
  - pip
  - pip:
    - pytest
    - pytest-flask
